# Generated by Django 4.2.6 on 2026-01-05 03:00

import apps.assessments.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0004_alter_space_access_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0015_topic_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("ES", "Spanish"),
                            ("FR", "French"),
                            ("DE", "German"),
                            ("IT", "Italian"),
                            ("PT", "Portuguese"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("minimum_requirements", models.TextField(blank=True, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.assessments.models.content_file_name,
                        validators=[apps.assessments.models.image_file_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_score",
                    models.PositiveIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "number_of_questions",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "allowed_attempts",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "difficulty",
                    models.FloatField(
                        default=5.0,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("user_difficulty_rating", models.FloatField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("attempts_count", models.IntegerField(default=0)),
                ("spaces", models.ManyToManyField(blank=True, related_name="assessments", to="spaces.space")),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.topic"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.assessments.models.question_audio_upload,
                        validators=[apps.assessments.models.audio_file_size],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.assessments.models.question_image_upload,
                        validators=[apps.assessments.models.image_file_size],
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.assessments.models.question_file_upload,
                        validators=[apps.assessments.models.general_file_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_multiple_choice", models.BooleanField(default=False)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_followed",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments_followed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("correct_answer", models.BooleanField(default=False)),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.assessments.models.choice_audio_upload,
                        validators=[apps.assessments.models.audio_file_size],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.assessments.models.choice_image_upload,
                        validators=[apps.assessments.models.image_file_size],
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="assessments.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentDifficultyRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "difficulty",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_ratings",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment difficulty rating",
                "verbose_name_plural": "Assessment difficulty ratings",
            },
        ),
        migrations.AddConstraint(
            model_name="followassessment",
            constraint=models.UniqueConstraint(fields=("follower", "assessment"), name="uq_rating_follower_assessment"),
        ),
        migrations.AddConstraint(
            model_name="assessmentdifficultyrating",
            constraint=models.UniqueConstraint(fields=("user", "assessment"), name="uq_rating_user_assessment"),
        ),
    ]
