# Generated by Django 4.2.6 on 2023-11-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_card_content_remove_card_image_and_more'),
        ('base', '0002_topictag_topic_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monster',
        ),
        migrations.AlterModelOptions(
            name='topictag',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='color',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='softskill',
            name='monster_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='softskill',
            name='monster_picture',
            field=models.ImageField(blank=True, null=True, upload_to='monsters_pics/'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='monster_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topictag',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
