# Generated by Django 4.2.6 on 2024-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mentor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='softskill',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
