# Generated by Django 4.2.6 on 2024-04-22 16:56

from django.db import migrations
from django.utils.text import slugify


def create_slugs(apps, schema_editor):
    Topic = apps.get_model("base", "Topic")
    topics = Topic.objects.all()
    used_slugs = set(Topic.objects.values_list("slug", flat=True))
    for topic in topics:
        if not topic.slug:
            title_words = topic.title.split()[:7]
            short_title = ' '.join(title_words)
            base_slug = slugify(short_title) or "topic"
            slug = base_slug
            count = 1
            while slug in used_slugs:
                slug = f"{base_slug}-{count}"
                count += 1
            topic.slug = slug
            topic.save()
            used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_topic_slug"),
    ]

    operations = [
        migrations.RunPython(create_slugs, reverse_code=migrations.RunPython.noop),
    ]
