# Generated by Django 4.2.6 on 2024-04-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_populate_topic_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=320, unique=True),
        ),
    ]
