# Generated by Django 4.2.6 on 2024-04-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
    ]
