# Generated by Django 4.2.6 on 2024-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_topic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
    ]
