# Generated by Django 4.2.6 on 2024-05-06 04:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_emailsending_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsending',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
