# Generated by Django 4.2.6 on 2024-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_emailsending_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsending',
            name='template',
            field=models.CharField(choices=[('send_info_with_username', 'Send Info with Username')], default='send_info_with_username', max_length=50),
        ),
    ]
