# Generated by Django 4.2.6 on 2024-09-21 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_mentors_for_existing_users(apps, schema_editor):
    user = apps.get_model(settings.AUTH_USER_MODEL)
    mentor = apps.get_model("base", "Mentor")

    for user in user.objects.all():
        if not hasattr(user, "mentor"):
            mentor.objects.create(user=user, created_by=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0013_emailsending_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_mentors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(create_mentors_for_existing_users),
    ]
