# Generated by Django 4.2.6 on 2023-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_card_content_remove_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['id'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
