# Generated by Django 4.2.6 on 2024-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='has_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
