# Generated by Django 4.2.6 on 2024-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_notification_has_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=320),
        ),
    ]
