# Generated by Django 4.2.6 on 2024-04-23 15:53

from django.db import migrations
from django.utils.text import slugify


def create_slugs(apps, schema_editor):
    Story = apps.get_model("blog", "Story")
    stories = Story.objects.all()
    used_slugs = set(Story.objects.values_list("slug", flat=True))
    for story in stories:
        if not story.slug:
            title_words = story.title.split()[:7]
            short_title = " ".join(title_words)
            base_slug = slugify(short_title) or "story"
            slug = base_slug
            count = 1
            while slug in used_slugs:
                slug = f"{base_slug}-{count}"
                count += 1
            story.slug = slug
            story.save()
            used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_story_slug"),
    ]

    operations = [
        migrations.RunPython(create_slugs, reverse_code=migrations.RunPython.noop),
    ]
