# Generated by Django 4.2.6 on 2024-05-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_usercardview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ask_for_help',
            field=models.BooleanField(default=False),
        ),
    ]
