# Generated by Django 4.2.6 on 2024-11-07 22:58

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_story_edited_time_story_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Amateur'), (3, 'Intermediate'), (4, 'Professional'), (5, 'Expert')], default=1),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.story_image_upload_path),
        ),
    ]
