# Generated by Django 4.2.6 on 2024-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_story_edited_time_story_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
