# Generated by Django 4.2.6 on 2024-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('blog', '0027_story_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='stories', to='spaces.space'),
        ),
    ]
