# Generated by Django 4.2.6 on 2024-11-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_story_difficulty_level_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('OT', 'Other')], default='FR', max_length=2),
        ),
    ]
