# Generated by Django 4.2.6 on 2024-11-22 01:18

from django.db import migrations, models


def populate_block_class(apps, schema_editor):
    Block = apps.get_model("blog", "Block")
    block_type_mapping = {
        "HERO": 1,
        "ATTACK": 2,
        "DEFENSE": 3,
        "INTERACTION": 4,
        "OBSERVATION": 5,
        "EVOLUTION": 6,
        "SCENE": 7,
        "WONDER": 8,
    }

    for block in Block.objects.all():
        if block.block_type and block.block_type.name in block_type_mapping:
            block.block_class = block_type_mapping[block.block_type.name]
        else:
            block.block_class = 1
        block.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_story_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="block_class",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "HERO"),
                    (2, "ATTACK"),
                    (3, "DEFENSE"),
                    (4, "INTERACTION"),
                    (5, "OBSERVATION"),
                    (6, "EVOLUTION"),
                    (7, "SCENE"),
                    (8, "WONDER"),
                ],
                default=1,
            ),
        ),
        migrations.RunPython(populate_block_class),
    ]
