# Generated by Django 4.2.6 on 2024-11-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_block_block_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='block_type',
        ),
    ]
