# Generated by Django 4.2.6 on 2024-11-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_block_block_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockType',
        ),
    ]
