# Generated by Django 4.2.6 on 2024-11-26 02:49

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_info_and_more'),
        ('blog', '0031_delete_blocktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profilecolor'),
        ),
        migrations.AddField(
            model_name='block',
            name='content_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='block',
            name='content_class',
            field=models.CharField(blank=True, choices=[('FACT', 'Fact'), ('MYTH', 'Myth'), ('OPINION', 'Opinion')]),
        ),
        migrations.AddField(
            model_name='block',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.block_image_upload_path),
        ),
        migrations.AddField(
            model_name='block',
            name='quoted_by',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='identity_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unspecified Identity'), (1, 'Instinctive Identity'), (2, 'Emotional Identity'), (3, 'Mental Identity')], null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='life_moment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unspecified Age'), (1, 'Aged 5 to 10'), (2, 'Aged 10 to 15'), (3, 'Aged 15 to 20'), (4, 'Aged 20 to 30'), (5, 'Aged 40 to 50'), (6, 'Aged 50 to 60'), (7, 'Aged 60 to 70'), (8, 'Aged 70 and more')], null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'STANDARD'), (2, 'MONSTER'), (3, 'MENTOR'), (4, 'HERO'), (5, 'HIGHLIGHT'), (6, 'QUOTE'), (7, 'FLASHCARD'), (8, 'FACT'), (9, 'WONDER'), (10, 'QUESTION'), (11, 'TESTIMONIAL'), (12, 'REFLECTION')], default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Amateur'), (3, 'Intermediate'), (4, 'Professional'), (5, 'Expert')], null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(blank=True, choices=[(None, 'Unspecified Language'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('OT', 'Other')], max_length=2),
        ),
    ]
