# Generated by Django 4.2.6 on 2024-12-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_block_content_2_alter_block_content_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
