# Generated by Django 4.2.6 on 2025-01-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_block_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
