# Generated by Django 4.2.6 on 2025-03-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_story_spaces'),
        ('blog', '0035_block_options'),
    ]

    operations = [
    ]
