# Generated by Django 4.2.6 on 2025-12-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_merge_0028_story_spaces_0035_block_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
