# Generated by Django 4.2.6 on 2026-01-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0037_alter_card_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_class",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "STANDARD"),
                    (2, "MONSTER"),
                    (3, "MENTOR"),
                    (4, "HERO"),
                    (5, "HIGHLIGHT"),
                    (6, "QUOTE"),
                    (7, "FLASHCARD"),
                    (8, "FACT"),
                    (9, "WONDER"),
                    (10, "QUESTION"),
                    (11, "TESTIMONIAL"),
                    (12, "REFLECTION"),
                    (13, "ILLUSTRATION"),
                    (14, "MULTICHOICE"),
                ],
                default=1,
            ),
        ),
    ]
