# Generated by Django 4.2.6 on 2026-02-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0038_alter_block_block_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="life_moment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, "Unspecified Age"),
                    (1, "Aged 5 to 10"),
                    (2, "Aged 10 to 15"),
                    (3, "Aged 15 to 20"),
                    (4, "Aged 20 to 30"),
                    (5, "Aged 30 to 40"),
                    (6, "Aged 40 to 50"),
                    (7, "Aged 50 to 60"),
                    (8, "Aged 60 to 70"),
                    (9, "Aged 70 and more"),
                ],
                null=True,
            ),
        ),
    ]
