# Generated by Django 4.2.6 on 2026-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0040_notification_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("reply", "Reply"), ("like", "Like"), ("level_up", "Level Up"), ("welcome", "Welcome")],
                max_length=20,
            ),
        ),
    ]
