# Generated by Django 4.2.6 on 2026-05-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0042_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reply", "Reply"),
                    ("like", "Like"),
                    ("level_up", "Level Up"),
                    ("welcome", "Welcome"),
                    ("coin_purchase_pending", "Coin Purchase Pending"),
                    ("coin_purchase_success", "Coin Purchase Success"),
                    ("item_purchase", "Item Purchase"),
                    ("color_purchase", "Color Purchase"),
                ],
                max_length=30,
            ),
        ),
    ]
