# Generated by Django 4.2.6 on 2023-10-16 17:12

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.users.models.MrvUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.content_file_name),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
