# Generated by Django 4.2.6 on 2024-02-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_experience_gender_profilecolor_customuser_biography_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experience'},
        ),
    ]
