# Generated by Django 4.2.6 on 2024-04-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_experience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_new_stories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_weekly_recalls',
            field=models.BooleanField(default=False),
        ),
    ]
