# Generated by Django 4.2.6 on 2024-05-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_email_info_customuser_email_new_stories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_new_stories',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_weekly_recalls',
            field=models.BooleanField(default=True),
        ),
    ]
