# Generated by Django 4.2.6 on 2025-01-24 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('VETERAN', 'Veteran'), ('STORYTELLER', 'Storyteller'), ('POPULAR', 'Popular'), ('COLLABORATOR', 'Collaborator'), ('EXPLORER', 'Explorer')], max_length=20)),
                ('level', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Obsidian', 'Obsidian'), ('Mixelo', 'Mixelo')], max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_type', 'level')},
            },
        ),
    ]
