# Generated by Django 4.2.6 on 2025-02-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_days',
            field=models.IntegerField(default=0),
        ),
    ]
