# Generated by Django 4.2.6 on 2026-02-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_average_score_customuser_points_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="coin_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="coin_last_updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
