# Generated by Django 4.2.6 on 2026-04-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_coin_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ActivityPoints",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_key",
                    models.CharField(
                        choices=[
                            ("view_story", "View Story"),
                            ("comment_story", "Comment Story"),
                            ("create_story", "Create Story"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_points_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activity Points",
                "indexes": [models.Index(fields=["user", "-created_at"], name="users_activ_user_id_c4f188_idx")],
            },
        ),
    ]
