# Generated by Django 4.2.6 on 2026-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_level_activitypoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
