# Generated by Django 4.2.6 on 2024-10-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="slug",
            field=models.SlugField(blank=True, max_length=320, unique=True),
        ),
    ]
