# Generated by Django 4.2.6 on 2024-11-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershiprequest',
            unique_together=set(),
        ),
    ]
