# Generated by Django 4.2.6 on 2025-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_membershiprequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free'), ('private', 'Private')], default='free', max_length=10),
        ),
    ]
