# Generated by Django 4.2.6 on 2025-08-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnlockedSkinColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_skin_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'color_code')},
            },
        ),
        migrations.CreateModel(
            name='UserUnlockedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('FACE', 'Face'), ('HAIR', 'Hair'), ('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('SHOES', 'Shoes'), ('ACCESSORY', 'Accessory')], max_length=20)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='UserUnlockedEyesColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_eyes_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'color_code')},
            },
        ),
        migrations.CreateModel(
            name='UserUnlockedColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'color_code')},
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_type', models.CharField(choices=[('BOY', 'Boy'), ('GIRL', 'Girl')], default='BOY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_for_accessory', to='avatar.userunlockedcolor')),
                ('accessory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_accessory', to='avatar.userunlockeditem')),
                ('eyes_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_for_eyes', to='avatar.userunlockedeyescolor')),
                ('face_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_as_face', to='avatar.userunlockeditem')),
                ('hair_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_for_hair', to='avatar.userunlockedcolor')),
                ('hair_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_as_hair', to='avatar.userunlockeditem')),
                ('pants_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_for_pants', to='avatar.userunlockedcolor')),
                ('pants_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_as_pants', to='avatar.userunlockeditem')),
                ('shirt_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_for_shirt', to='avatar.userunlockedcolor')),
                ('shirt_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_as_shirt', to='avatar.userunlockeditem')),
                ('shoes_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_for_shoes', to='avatar.userunlockedcolor')),
                ('shoes_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_as_shoes', to='avatar.userunlockeditem')),
                ('skin_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_for_skin', to='avatar.userunlockedskincolor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
