# Generated by Django 4.2.6 on 2025-08-07 14:25

from django.db import migrations


def create_default_avatars(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")
    UserUnlockedItem = apps.get_model("avatar", "UserUnlockedItem")
    UserUnlockedColor = apps.get_model("avatar", "UserUnlockedColor")
    UserUnlockedSkinColor = apps.get_model("avatar", "UserUnlockedSkinColor")
    UserUnlockedEyesColor = apps.get_model("avatar", "UserUnlockedEyesColor")
    Avatar = apps.get_model("avatar", "Avatar")

    for user in User.objects.all():
        if hasattr(user, "avatar"):
            continue

        face_item = UserUnlockedItem.objects.create(user=user, item_code="BOY_FACE_1", item_type="FACE")
        hair_item = UserUnlockedItem.objects.create(user=user, item_code="BOY_HAIR_1", item_type="HAIR")
        shirt_item = UserUnlockedItem.objects.create(user=user, item_code="BOY_SHIRT_1", item_type="SHIRT")
        pants_item = UserUnlockedItem.objects.create(user=user, item_code="BOY_PANT_1", item_type="PANTS")
        shoes_item = UserUnlockedItem.objects.create(user=user, item_code="BOY_SHOE_1", item_type="SHOES")

        UserUnlockedItem.objects.create(user=user, item_code="GIRL_FACE_1", item_type="FACE")
        UserUnlockedItem.objects.create(user=user, item_code="GIRL_HAIR_1", item_type="HAIR")
        UserUnlockedItem.objects.create(user=user, item_code="GIRL_SHIRT_1", item_type="SHIRT")
        UserUnlockedItem.objects.create(user=user, item_code="GIRL_PANT_1", item_type="PANTS")
        UserUnlockedItem.objects.create(user=user, item_code="GIRL_SHOE_1", item_type="SHOES")

        color = UserUnlockedColor.objects.create(user=user, color_code="BLACK")
        skin_color = UserUnlockedSkinColor.objects.create(user=user, color_code="SKIN_LIGHT")
        eyes_color = UserUnlockedEyesColor.objects.create(user=user, color_code="BLACK")
        Avatar.objects.create(
            user=user,
            face_item=face_item,
            hair_item=hair_item,
            hair_color=color,
            shirt_item=shirt_item,
            shirt_color=color,
            pants_item=pants_item,
            pants_color=color,
            shoes_item=shoes_item,
            shoes_color=color,
            eyes_color=eyes_color,
            skin_color=skin_color,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_avatars),
    ]
