# Generated by Django 4.2.6 on 2026-02-08 23:47

from django.conf import settings
from django.db import migrations, models


def reset_avatar_data(apps, schema_editor):
    Avatar = apps.get_model("avatar", "Avatar")
    UserUnlockedItem = apps.get_model("avatar", "UserUnlockedItem")
    UserUnlockedColor = apps.get_model("avatar", "UserUnlockedColor")
    UserUnlockedSkinColor = apps.get_model("avatar", "UserUnlockedSkinColor")
    UserUnlockedEyesColor = apps.get_model("avatar", "UserUnlockedEyesColor")

    Avatar.objects.all().delete()
    UserUnlockedItem.objects.all().delete()
    UserUnlockedColor.objects.all().delete()
    UserUnlockedSkinColor.objects.all().delete()
    UserUnlockedEyesColor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("avatar", "0002_create_default_avatar_for_existing_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarColorCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hex", models.CharField(max_length=7)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AvatarSkinColorCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_color", models.CharField(max_length=7)),
                ("second_color", models.CharField(max_length=7)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AvatarItemCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("FACE", "Face"),
                            ("HAIR", "Hair"),
                            ("SHIRT", "Shirt"),
                            ("PANTS", "Pants"),
                            ("SHOES", "Shoes"),
                            ("ACCESSORY", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("avatar_type", models.CharField(choices=[("BOY", "Boy"), ("GIRL", "Girl")], max_length=20)),
                ("svg", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["item_type", "avatar_type", "is_active"], name="avatar_avat_item_ty_1485fc_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(reset_avatar_data, migrations.RunPython.noop),
    ]
