# Generated by Django 4.2.6 on 2026-02-08 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("avatar", "0003_avatarcolorcatalog_avatarskincolorcatalog_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userunlockedcolor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userunlockeditem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userunlockedskincolor",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userunlockedcolor",
            name="catalog_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unlocks",
                to="avatar.avatarcolorcatalog",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userunlockeditem",
            name="catalog_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unlocks",
                to="avatar.avataritemcatalog",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userunlockedskincolor",
            name="catalog_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unlocks",
                to="avatar.avatarskincolorcatalog",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="userunlockedcolor",
            name="color_code",
        ),
        migrations.RemoveField(
            model_name="userunlockeditem",
            name="item_code",
        ),
        migrations.RemoveField(
            model_name="userunlockeditem",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="userunlockedskincolor",
            name="color_code",
        ),
    ]
