# Generated by Django 4.2.6 on 2026-02-08 23:47

from django.conf import settings
from django.db import migrations


def seed_catalogs(apps, schema_editor):
    """
    Crea los registros del catálogo basándose en los diccionarios.
    """
    AvatarItemCatalog = apps.get_model("avatar", "AvatarItemCatalog")
    AvatarColorCatalog = apps.get_model("avatar", "AvatarColorCatalog")
    AvatarSkinColorCatalog = apps.get_model("avatar", "AvatarSkinColorCatalog")

    from apps.avatar.items.avatar_items import AVATAR_ITEMS
    from apps.avatar.items.skin_colors import SKIN_COLORS
    from apps.avatar.items.item_colors import COLORS

    # Items
    for item_type, items in AVATAR_ITEMS.items():
        for _, payload in items.items():
            AvatarItemCatalog.objects.update_or_create(
                code=payload["code"],
                defaults={
                    "name": payload["name"],
                    "svg": payload["svg"],
                    "item_type": item_type,
                    "avatar_type": payload["gender"],
                    "price": 20,
                    "is_active": True,
                    "sort_order": 0,
                },
            )

    # Colors
    for code, payload in COLORS.items():
        AvatarColorCatalog.objects.update_or_create(
            code=code,
            defaults={
                "name": payload["name"],
                "hex": payload["hex"],
                "price": 10,
                "is_active": True,
                "sort_order": 0,
            },
        )

    # Skin colors
    for code, payload in SKIN_COLORS.items():
        AvatarSkinColorCatalog.objects.update_or_create(
            code=code,
            defaults={
                "name": payload["name"],
                "main_color": payload["main_color"],
                "second_color": payload["second_color"],
                "price": 10,
                "is_active": True,
                "sort_order": 0,
            },
        )


def create_default_avatars_from_catalog(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")

    Avatar = apps.get_model("avatar", "Avatar")
    UserUnlockedItem = apps.get_model("avatar", "UserUnlockedItem")
    UserUnlockedColor = apps.get_model("avatar", "UserUnlockedColor")
    UserUnlockedSkinColor = apps.get_model("avatar", "UserUnlockedSkinColor")
    UserUnlockedEyesColor = apps.get_model("avatar", "UserUnlockedEyesColor")

    AvatarItemCatalog = apps.get_model("avatar", "AvatarItemCatalog")
    AvatarColorCatalog = apps.get_model("avatar", "AvatarColorCatalog")
    AvatarSkinColorCatalog = apps.get_model("avatar", "AvatarSkinColorCatalog")

    face_boy = AvatarItemCatalog.objects.get(code="BOY_FACE_1")
    hair_boy = AvatarItemCatalog.objects.get(code="BOY_HAIR_1")
    shirt_boy = AvatarItemCatalog.objects.get(code="BOY_SHIRT_1")
    pants_boy = AvatarItemCatalog.objects.get(code="BOY_PANT_1")
    shoes_boy = AvatarItemCatalog.objects.get(code="BOY_SHOE_1")

    face_girl = AvatarItemCatalog.objects.get(code="GIRL_FACE_1")
    hair_girl = AvatarItemCatalog.objects.get(code="GIRL_HAIR_1")
    shirt_girl = AvatarItemCatalog.objects.get(code="GIRL_SHIRT_1")
    pants_girl = AvatarItemCatalog.objects.get(code="GIRL_PANT_1")
    shoes_girl = AvatarItemCatalog.objects.get(code="GIRL_SHOE_1")

    black = AvatarColorCatalog.objects.get(code="BLACK")
    skin_light = AvatarSkinColorCatalog.objects.get(code="SKIN_LIGHT")

    for user in User.objects.all().iterator():
        if hasattr(user, "avatar"):
            continue

        face_item = UserUnlockedItem.objects.create(user=user, catalog_item=face_boy)
        hair_item = UserUnlockedItem.objects.create(user=user, catalog_item=hair_boy)
        shirt_item = UserUnlockedItem.objects.create(user=user, catalog_item=shirt_boy)
        pants_item = UserUnlockedItem.objects.create(user=user, catalog_item=pants_boy)
        shoes_item = UserUnlockedItem.objects.create(user=user, catalog_item=shoes_boy)

        UserUnlockedItem.objects.create(user=user, catalog_item=face_girl)
        UserUnlockedItem.objects.create(user=user, catalog_item=hair_girl)
        UserUnlockedItem.objects.create(user=user, catalog_item=shirt_girl)
        UserUnlockedItem.objects.create(user=user, catalog_item=pants_girl)
        UserUnlockedItem.objects.create(user=user, catalog_item=shoes_girl)

        color = UserUnlockedColor.objects.create(user=user, catalog_item=black)
        skin_color = UserUnlockedSkinColor.objects.create(user=user, catalog_item=skin_light)

        eyes_color = UserUnlockedEyesColor.objects.create(user=user, color_code="BLACK")

        Avatar.objects.create(
            user=user,
            face_item=face_item,
            hair_item=hair_item,
            hair_color=color,
            shirt_item=shirt_item,
            shirt_color=color,
            pants_item=pants_item,
            pants_color=color,
            shoes_item=shoes_item,
            shoes_color=color,
            eyes_color=eyes_color,
            skin_color=skin_color,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("avatar", "0004_alter_schema_and_seed_catalogs"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userunlockedcolor",
            unique_together={("user", "catalog_item")},
        ),
        migrations.AlterUniqueTogether(
            name="userunlockeditem",
            unique_together={("user", "catalog_item")},
        ),
        migrations.AlterUniqueTogether(
            name="userunlockedskincolor",
            unique_together={("user", "catalog_item")},
        ),
        migrations.RunPython(seed_catalogs, migrations.RunPython.noop),
        migrations.RunPython(create_default_avatars_from_catalog, migrations.RunPython.noop),
    ]
