# Generated by Django 4.2.6 on 2026-03-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("avatar", "0005_set_unique_constraints_and_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="ki_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_for_ki",
                to="avatar.userunlockedcolor",
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="ki_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_as_ki",
                to="avatar.userunlockeditem",
            ),
        ),
        migrations.AlterField(
            model_name="avataritemcatalog",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("FACE", "Face"),
                    ("HAIR", "Hair"),
                    ("SHIRT", "Shirt"),
                    ("PANTS", "Pants"),
                    ("SHOES", "Shoes"),
                    ("ACCESSORY", "Accessory"),
                    ("KI", "Ki"),
                ],
                max_length=20,
            ),
        ),
    ]
